### ISSUE TITLE
libclass_loader.so error

### ISSUE THREAD

**Issue by ghthdckfid** [Krishtof-Korda/pcap-to-bag#1]
i got 
./pcap_to_bag: error while loading shared libraries: libclass_loader.so: cannot open shared object file: No such file or directory
this message 
how can i solve it

**Comment by Krishtof-Korda** [comment]
@ghthdckfid 

I've never seen this before. As far as I know we don't have this file in any of our code.
Are you using this in combination with Ouster_example?

What are the steps you are doing to recreate this?

**Comment by blakely3dnm** [comment]
Hi, 

I have the same issue. I am running ROS melodic and Ubuntu 18.04. ouster_example works as intended. 
To compile I had to install libpcap-dev and libtins-dev from ppm, however attempting to run the binary fails with `error while loading shared libraries: libclass_loader.so: cannot open shared object file: No such file or directory`

**Comment by shuangxing93** [comment]
You need to source your ROS environment before running ./pcap_to_bag, it should fix the issue.

`source /opt/ros/<distro>/setup.bash`
