### ISSUE TITLE
Illegal Instruction (core dumped)

### ISSUE THREAD

**Issue by CantLooseToAMoose** [Krishtof-Korda/pcap-to-bag#13]
Hello,

when trying to run the program I only get an "Illegal Instruction (core dumped)" error message. This might be because I am using a Virtual Machine. Anyone have an idea how to fix it? What system has this been tested on?

Thanks in advance.

**Comment by CantLooseToAMoose** [comment]
I found a solution. It seems the avx instruction set gets lost when using a windows host machine with Hyper V enabled. 
Look at https://stackoverflow.com/questions/65780506/how-to-enable-avx-avx2-in-virtualbox-6-1-16-with-ubuntu-20-04-64bit for more information.

**Comment by Krishtof-Korda** [comment]
I'm glad you were able to find a solution. We have a new developer
community that is a good place to share this type of information. We'd love
for you to join.
https://community.ouster.com
