### ISSUE TITLE
CMake Error | pcap_to_bag

### ISSUE THREAD

**Issue by pavankumarbn** [Krishtof-Korda/pcap-to-bag#2]
Hi,
I am trying to convert pcap file to bag using this code. I am facing this error ` Could not find a package configuration file provided by "ouster_ros" with any of the following names: ouster_rosConfig.cmake ouster_ros-config.cmake` could you please let me know how to fix this issue?

**Comment by Krishtof-Korda** [comment]
Hi!

Have you properly linked `ouster_example` in the same workspace as `pcap-to-bag`?

**Comment by pavankumarbn** [comment]
Hi, Thank you. Not yet..

**Comment by jeychandar** [comment]
Hi I am new to this. Could you please explain how you installed this. I am confused and I am stuck. 
![image](https://user-images.githubusercontent.com/48254471/212469129-1242dc97-cdb8-4bde-aca5-a8d62dc491f2.png)
