### ISSUE TITLE
Extract Data

### ISSUE THREAD

**Issue by LihaoQiu** [Krishtof-Korda/pcap-to-bag#3]
Hi!
First of all, thank you for sharing this github. 
I found out that in the converted PCD file, there are only two topics: os1_node/imu_packets and os1_node.lidar_packets. I used to record data with ouster-example directly using os_cloud_node/points and I don't know how to extract data now. Could you tell me how to extract point data now? Thank you very much!

**Comment by Krishtof-Korda** [comment]
Hi!

Once you have the bag file with the `os1_node/imu_packets` and `os1_node/lidar_packets`, you need to `rosbag play` the bag in the `ouster_ros` node and `rosbag record` `os_cloud_node/points`. This will generate a bag with the points topic.
