### ISSUE TITLE
datatype/md5sum

### ISSUE THREAD

**Issue by Ali-Darzi** [Krishtof-Korda/pcap-to-bag#5]
Hi, I converted the Pcap file to bag to use it in [Fast-LIO_SLAM](https://github.com/gisbi-kim/FAST_LIO_SLAM), but I get the following error.
[ERROR] [1652370710.955314568]: Client [/laserMapping] wants topic /os_node/lidar_packets to have datatype/md5sum [sensor_msgs/PointCloud2/1158d486dd51d683ce2f1be655c3c181], but our version has [ouster_ros/PacketMsg/4f7b5949e76f86d01e96b0e33ba9b5e3]. Dropping connection.

it seems that datatype/md5sum is the problem. is there an easy fix for it?

**Comment by Ali-Darzi** [comment]
I figured out that the bag contains the topics from os_node (which are imu_packets and lidar_packets). While the topics of os_cloud_node are needed (imu and points). Could you add os_cloud_node code to the conversion with the option of selecting either nodes?

**Comment by Krishtof-Korda** [comment]
Hi @Ali-Darzi ,

You are exactly correct about which topics are published and that is by design to minimize the file size. 

I have updated the instructions in the readme with how to create the topics with the points in them. 

Cheers,
Krishtof

**Comment by Ali-Darzi** [comment]
Thanks Krishtof,
The solution was simple and effective. 

Ali
