### ISSUE TITLE
No lidar packets

### ISSUE THREAD

**Issue by knurgazy** [Krishtof-Korda/pcap-to-bag#7]
Hello!

I am trying to convert pcap files to bag, and after running the command, I have the following result:
"""Written 0 lidar packets and 9602 imu packets
     Duration: 96.0244 seconds"""

Could you please help with this issue, why it wrote 0 packets

**Comment by Krishtof-Korda** [comment]
Hi,

You need to very that the lidar port in the pcap matches the hard coded one
in pcap to bag. If not, please change the lidar port in the code.

**Comment by Priya4120** [comment]
I am also facing the same issue. I was able to to locate the port in pcap file but I was not able to figure where the hard coded port number is located in pcap-to-bag repo. Could you point me where can I find it? Thank you.

**Comment by Krishtof-Korda** [comment]
My apologies, I meant the hardcoded lidar_payload_size. The size needs to
match your lidar packet size.

**Comment by dariusz-flasheye** [comment]
Hello,

Facing exactly the same issue like in previous posts. Can you explain with some example, how to correct it? I'm trying to convert pcap data with the new Ouster OS Dome 128 lidar. I'm getting IMU packets, but no lidar packets in the rosbag.

As I understand those hardcoded variables needs to be changed, but how to get proper ones for the data I want to convert?

```
  uint32_t azimuths_per_packet = 16;
  uint32_t num_header_footer_words = 5;
  uint32_t bytes_per_word = 4;
  uint32_t words_per_channel = 3;
```

**Comment by Krishtof-Korda** [comment]
@dariusz-flasheye ,

It depends on what udp_profile_lidar your data was collected in. Can you share a link to the .json file for the data you're trying to convert?
Thanks.

**Comment by dariusz-flasheye** [comment]
Sure!

[Sample Data | OS-DOME 128 | Preliminary Data - Prototype](https://flasheye-my.sharepoint.com/:u:/g/personal/dariusz_flasheye_se/EfKiQrW37cdJuxN4j-MFxuwBaaTGZYUS27xPPfueVATRwg?e=4Fx4cn)

**Comment by Krishtof-Korda** [comment]
@dariusz-flasheye ,
Based on the json your profile is dual return.
According to the Ouster manual you can calculate the packet size using [this calculator](https://static.ouster.dev/sensor-docs/image_route1/image_route2/sensor_data/sensor-data.html#packet-size-calculation-configurable) 

 "udp_profile_lidar": "RNG19_RFL8_SIG16_NIR16_DUAL"

So for you, 32+16*(12+128*16)+32=33024 bytes.
You can just directly declare lidar_payload_size=33024.

**Comment by dariusz-flasheye** [comment]
Great! Thank you for your help. Got it to work now.
